### ISSUE TITLE
test brake & clutch pedals

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen154hyundai#49]
Remove R

Add a jumper wire between connector side of R and 

![image](https://user-images.githubusercontent.com/48498823/146570511-29f6a063-637e-4880-8d96-a3b8d6943bcd.png)

![image](https://user-images.githubusercontent.com/48498823/146570407-79932b0f-4e23-4d15-896a-c01f649b20ec.png)

Note added to https://github.com/andreika-git/hellen-one/wiki/module-input

**Comment by ElDominio** [comment]
<img width="961" alt="image" src="https://user-images.githubusercontent.com/5685108/146625293-a9f1bc82-494e-42bc-9f71-6053ca9e28df.png">

brake pedal i can't check if it's working or not since it's crossed out
[pressingbrake.zip](https://github.com/rusefi/hellen154hyundai/files/7738542/pressingbrake.zip)


pressingbrake is a log of me pressing brake pedal

**Comment by mck1117** [comment]
right click dash -> load/save -> load dashboard -> pick default in dropdown (should be picked already) -> OK

**Comment by ElDominio** [comment]
kk, brake works

didn't know i needed to reload the dashboard lol

**Comment by mck1117** [comment]
We changed some stuff recently that necessitated a one-time dashboard reload.  Doesn't happen on new projects.

**Comment by ElDominio** [comment]
Clutch input works on newest firmware

**Comment by rusefillc** [comment]
Sounds like we are happy and can close @ElDominio ?

**Comment by ElDominio** [comment]
Yessir, good to close
